### ISSUE TITLE
Why is versioning jumps from 2.x to 1.1?

### ISSUE THREAD

**Issue by hadizainudin** [barc/express-hbs#158]
I don't have any issue with anything, just that I can't find necessary changelog, and I wonder why versioning jumps from 1.0.4 to 2.x to 1.1 again. Thank you and have a great day.

**Comment by ErisDS** [comment]
@allouis confirmed this even on npm

**Comment by franck34** [comment]
When we npm `install express-hbs` with or without `--save-exact` options, it will put version in package.json.

Many project badges related to package up-to-date dependencies will give a false positive if you go down in versioning.

Another example, in package.json, if version is ```^```2.0.2, [ncu](https://github.com/tjunnone/npm-check-updates) will not be able to say that there is a new release, because new release got a version lower than the previous one.

Yes, you have to release with a version > previous version, i.e 2.1.1.

<troll>
Stop smoking weed
</troll>

Btw, big thanks and long live to hbs and express-hbs

**Comment by franck34** [comment]
I'm using this package in many project, and i can confirme that NCU (npm check updates) don't see the new version, it say i'm up to date.

**Comment by allouis** [comment]
I put down the joint and release 2.1.1 - let me know if this is still an issue :+1:
