### ISSUE TITLE
Subexpressions don't work as expected

### ISSUE THREAD

**Issue by halfdan** [barc/express-hbs#56]
This is a follow up on #55 but might not directly be related.

Using sub-expressions like `{{encode (url)}}` (as in https://github.com/halfdan/hbs-weird/) where the url helper returns a URL and encode executes encodeURIComponent the expression is replaced by only the result of the url helper. Using `{{encode "http://foo.bar/?baz=muh"}}` on its own seems to work just fine.

Example case in https://github.com/halfdan/hbs-weird/

**Comment by nknapp** [comment]
Could you have a look at [promised-handlebars](https://github.com/nknapp/promised-handlebars). I have written it in the past week and I have working test-cases for nesting async helpers within async block-helpers.  Though, it has not been tested on larger examples yet.
Any feedback is appreciated.

**Comment by mgutz** [comment]
Will do. I might not be able to look at it for at least several days though.

**Comment by nknapp** [comment]
I think, `promised-handlebars` now has all the features I would expect from it.
The following cases all work with sync- and async-helpers in all combinations,
where "async" means that the helper returns a promise for the value rather than the value itself.
* Simple helper calls `{{{helper arg}}}`
* HTML-Escaping the result `{{helper arg}}`
* Nesting helpers in parameters {{helper (nested-helper)}}
* Helpers called from within block helpers: {{#block-helper}}{{inner-helper}}{{/block-helper}}
* Usage with built-in helpers `{{#if (nested helper)}}abc{{/if}}`
* Helpers as hash arguments `{{helper param=(nested-helper) }}`

**Comment by nknapp** [comment]
@mgutz have you had any chance to look at it?

**Comment by bradvogel** [comment]
Bump

**Comment by jtwebman** [comment]
This is fixed now with my latest merge.
