### ISSUE TITLE
hbs instance  registerAsyncHelper weird hash

### ISSUE THREAD

**Issue by mquintal** [barc/express-hbs#60]
Hi! I have an issue using `registerAsyncHelper`.  I need compile a layout in restrict scope because of this I've created a new Handlebars instance and I've created a helper in this instance. But when I compile the layout it returns a weird hash.
My code is something like this: 

```
var hbs_temp = hbs.create();

hbs_temp.registerAsyncHelper( 'content', function( text, cb ) {     
    fs.readFile( 'some-file', { encoding: 'utf8' }, function( err, data ) {
        cb( new hbs_temp.SafeString( data ) );
    });
});
```

`hbs_temp.compile( '<div> {{content}} </div>' )(  );`

Result: 

`<div> __WEIRD HASH__ </div>`

My question is. I've something wrong in my code or this is a handlebar bug?
Thank you!

**Comment by F4b1n0u** [comment]
I have the same issue, I guess it's because the async feature is not compatible with the partial loading :s, I solve my issue buy decompose the thing in two step, first register all the partials with the registerPartial function, but it's need to know all the dependency in terms of partial.
and after that I can process my code. and there are other async partial call in this partials by the way, but they don't load partial.

I hope it's could help you :)
