### ISSUE TITLE
Can I add options for handlebars compiler?

### ISSUE THREAD

**Issue by harttle** [barc/express-hbs#73]
handlebars will auto-indent partials. It becomes undesirable in `<pre>` and `markdown`. See this issue:

https://github.com/wycats/handlebars.js/issues/858

handlebars compiler added preventIndent option, see:

https://github.com/wycats/handlebars.js/commit/632fadcea39b6328983c459ff7e8c4010a976837

I'll appreciate it if you can provide someway to add this compiler option, thanks.

**Comment by mgutz** [comment]
please test branch issue-73, see test/issues.js

**Comment by harttle** [comment]
great work! it works fine.

**Comment by ErisDS** [comment]
Hey, I tried to implement this new compiler option in Ghost, by upgrading express-hbs, and adding the onCompile function here: https://github.com/TryGhost/Ghost/blob/master/core/server/middleware/index.js#L55

However, the option is going missing somewhere. I'm trying to trace it through and I can't figure out what's going wrong. In compiler.js, the option is present in `compileInput` but not in `PartialStatement` - so I'm thinking this is a handlebars issue rather than a problem here, but thought I'd start here in case someone knows different.

**Comment by mgutz** [comment]
I'm not seeing onCompile overridden there. Is it on a different branch?

**Comment by ErisDS** [comment]
@mgutz Sorry, it's here: https://github.com/ErisDS/Ghost/commit/cf9eb5bc4d4853140e30a078ab6ce29453620738

It's identical to the example code and the express-hbs test for the functionality works for me just fine. Very odd.

**Comment by ErisDS** [comment]
I got this figured out :)

The example of `onCompile` wraps the passing of `preventIndent` in an if statement which checks whether the thing about to be compiled is a partial:

```
  onCompile: function(exhbs, source, filename) {
    var options;
    if (filename && filename.indexOf('partials') > -1) {
      options = {preventIndent: true};
    }
    return exhbs.handlebars.compile(source, options);
  }
```

However, the `preventIndent` option needs to be applied to the template which calls the partial, rather than the partial itself, as far as I can tell.

Therefore the following works as expected:

```
  onCompile: function(exhbs, source) {
     return exhbs.handlebars.compile(source, {preventIndent: true});
  }
```

**Comment by mgutz** [comment]
That makes sense. I was showing how to filter using the filename. I apologize for the side effects of passing that filename though. Caused at least two issues for you.

**Comment by ErisDS** [comment]
No problem, I'm enjoying getting more familiar with the `express-hbs` codebase :)
