### ISSUE TITLE
can I set a  variable in a helper use by other helper in one page?

### ISSUE THREAD

**Issue by elover** [barc/express-hbs#80]

**Comment by ErisDS** [comment]
This is a handlebars question, rather than anything to do with `express-hbs` :wink: 

Handlebars does not support the setting of variables. The only feature that works slightly like this is that partials can be passed options. So if you include a partial called `my-partial` like this:

{{> my-partial foo="bar"}}

Then `{{foo}}` will output 'bar' inside that partial.

**Comment by elover** [comment]
but it some like  helper "contentFor" and "block"
