### ISSUE TITLE
Doesn't throw errors when there is a compilation error

### ISSUE THREAD

**Issue by ktkaushik** [barc/express-hbs#90]
This is really important. There are times when the page is blatantly just loading and causes too many pain points.

**Comment by ErisDS** [comment]
@ktkaushik sorry to hear you're having trouble. Could you please provide a reproduction case so that it's clear what you're referring to?

**Comment by ktkaushik** [comment]
This one below for an example - Compiling a hbs which has typo in if case should throw an error, right ?

```javascript
{{#if user.username}}
   -- Do Something here

{{elsee}}

  -- Flash message here
{{/if}}
```

Shouldn't something like this throw an error of some sort ?

Another great example would be the typo in the __partials path__

```javascript
{{> /dashboard/activities}}
```

instead of 

```javascript
{{> dashboard/activities}}
```

Is there any solution ?

Thanks

**Comment by ErisDS** [comment]
As far as I am aware, this correct and inline with how the underlying handlebars library works:

Template compilation does not throw an error. Rather, errors are thrown when the compiled template is executed with some data. Only when you have the data, i.e. the context in which the template is executed, are you fully able to determine all the possible errors which might occur.

Handlebars has another method - `precompile` which does throw syntax errors in advance of having data.

Assuming you're using express-hbs in an express app and expecting template errors to occur when the server starts, rather than when a is page rendered, then I'd suggest you build a precompile step into your build process to detect any errors before the server is even started?

**Comment by ktkaushik** [comment]
@ErisDS I will try the `precompile` today in a grunt task and get back to you.

Thanks :)

**Comment by ErisDS** [comment]
@ktkaushik did that solve it?

**Comment by ktkaushik** [comment]
@ErisDS no, the precompile didn't really solve it. I wonder why though.

**Comment by ktkaushik** [comment]
I used grunt-handlebars to precompile but no luck

**Comment by jtwebman** [comment]
IS this still an issue with the latest?

**Comment by ErisDS** [comment]
Closing out all old issues. If this is still an issue with the latest version please let us know.
